CREATE TABLE config (
    key TEXT NOT NULL PRIMARY KEY,
    value TEXT NOT NULL
);
CREATE TABLE rooms (
    room_id INTEGER NOT NULL PRIMARY KEY,
    codename TEXT NOT NULL UNIQUE,
    channel_id TEXT NOT NULL UNIQUE,
    user_id TEXT NOT NULL UNIQUE
);
